baseURL = "http://example.org/"
languageCode = "en-us"
title = "Sample Hugo Website"
enableRobotsTXT = true

disableKinds = ["taxonomy", "term"]

[params]
  description = "A small sample website built with Hugo."
  # Set this to your form provider endpoint (e.g., Formspree/Getform/etc).
  # If left empty, the form will render but the submit button will be disabled.
  supporters_form_action = ""
  supporters_form_method = "POST"

[menu]
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    pageRef = "/about"
    weight = 2

  [[menu.main]]
    name = "Services"
    pageRef = "/services"
    weight = 3

  [[menu.main]]
    name = "Contact"
    pageRef = "/contact"
    weight = 4

  [[menu.main]]
    name = "Supporters"
    pageRef = "/supporters"
    weight = 5
